<?php

/**
 * @file
 * Contains rest_oai_pmh.module.
 *
 * @todo load metatag_dc config elements for creator and subject and set multiple = TRUE
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function rest_oai_pmh_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the rest_oai_pmh module.
    case 'help.page.rest_oai_pmh':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Exposes schema.org dublin core mappings in an OAI-PMH endpoint') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_rest_resource_alter().
 */
function rest_oai_pmh_rest_resource_alter(&$definitions) {
  // if the repository admin set a path, override the default URI
	$path = \Drupal::config('rest_oai_pmh.settings')->get('repository_path');
  if ($path) {
  	$definitions['oai_pmh']['uri_paths']['canonical'] = $path;
  }
}
